### ISSUE TITLE
Error when compiling the file. 

### ISSUE THREAD

**Issue by cuddlyJester** [hax0r31337/denpk2#2]
Hello! I'm trying to compile the file via MSCV. I used "cargo build", OPEN SSL libraries are installed, c++ and rust libraries too.
But i get this error message when compiling:

error[E0432]: unresolved import std::os::fd
 --> src\mmap.rs:1:14
  |
1 | use std::os::fd::AsRawFd;
  |              ^^ could not find fd in os

error[E0425]: cannot find function mmap in crate libc
 --> src\mmap.rs:7:15
  |
7 |         libc::mmap(
  |               ^^^^ not found in libc

error[E0425]: cannot find value PROT_READ in crate libc
  --> src\mmap.rs:10:19
   |
10 |             libc::PROT_READ,
   |                   ^^^^^^^^^ not found in libc

error[E0425]: cannot find value MAP_PRIVATE in crate libc
  --> src\mmap.rs:11:19
   |
11 |             libc::MAP_PRIVATE,
   |                   ^^^^^^^^^^^ not found in libc

error[E0425]: cannot find value MAP_FAILED in crate libc
  --> src\mmap.rs:17:24
   |
17 |     if mapped == libc::MAP_FAILED {
   |                        ^^^^^^^^^^ not found in libc

error[E0599]: no method named as_raw_fd found for struct std::fs::File in the current scope
  --> src\mmap.rs:12:18
   |
12 |             file.as_raw_fd(),
   |                  ^^^^^^^^^
   |
help: there is a method as_raw_handle with a similar name
   |
12 |             file.as_raw_handle(),
   |                  ~~~~~~~~~~~~~

Can you please help me?

**Comment by hax0r31337** [comment]
I utilizes [mmap](https://man7.org/linux/man-pages/man2/mmap.2.html) instead of reading the file to make it faster and consumes as less RAM as possible, which breaks support on non-unix OSes such as Windows.

**Comment by cuddlyJester** [comment]
Is there a way i can run this into windows?

**Comment by cuddlyJester** [comment]
What should i put in the code instead of "mmap" for windows?

**Comment by hax0r31337** [comment]
Windows support added
