### ISSUE TITLE
Error when compiling the file on linux

### ISSUE THREAD

**Issue by cuddlyJester** [hax0r31337/denpk2#3]
──(kali㉿kali)-[~/Documents/idv/denpk2 
└─$ cargo run  
    Finished dev profile [unoptimized + debuginfo] target(s) in 0.05s
     Running target/debug/denpk2
Error: Os { code: 2, kind: NotFound, message: "No such file or directory"}

How can i fix that?

**Comment by hax0r31337** [comment]
read the main.rs code pls
